title: Radar Documentation
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

search_enabled: true

nav:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Usage
    url: /usage
